import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowDown, ArrowLeft, ArrowUp, MapPin, Pencil, Plus, Trash2, X } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router-dom'

import { api } from '../../lib/api'
import { ConfirmDialog } from '../../components/ui/ConfirmDialog'

export function RoutesPage() {
  const queryClient = useQueryClient()
  const routes = useQuery({ queryKey: ['routes'], queryFn: api.routes })
  const [creating, setCreating] = useState(false)
  const [name, setName] = useState('新的路线清单')
  const [editing, setEditing] = useState<string>()
  const [editingName, setEditingName] = useState('')
  const [deleting, setDeleting] = useState<{ id: string; name: string }>()
  const create = useMutation({ mutationFn: () => api.createRoute(name, ''), onSuccess: () => { setCreating(false); void queryClient.invalidateQueries({ queryKey: ['routes'] }) } })
  const reorder = useMutation({ mutationFn: ({ routeId, ids }: { routeId: string; ids: string[] }) => api.updateRoute(routeId, ids), onSuccess: () => void queryClient.invalidateQueries({ queryKey: ['routes'] }) })
  const rename = useMutation({ mutationFn: ({ routeId, city }: { routeId: string; city: string }) => api.updateRouteMetadata(routeId, editingName, city), onSuccess: () => { setEditing(undefined); void queryClient.invalidateQueries({ queryKey: ['routes'] }) } })
  const removeRoute = useMutation({ mutationFn: api.deleteRoute, onSuccess: () => { setDeleting(undefined); void queryClient.invalidateQueries({ queryKey: ['routes'] }); void queryClient.invalidateQueries({ queryKey: ['map'] }) } })
  const move = (routeId: string, ids: string[], index: number, offset: number) => { const next = index + offset; if (next < 0 || next >= ids.length) return; const reordered = [...ids]; [reordered[index], reordered[next]] = [reordered[next], reordered[index]]; reorder.mutate({ routeId, ids: reordered }) }
  return <div className="page-frame route-page"><header className="detail-topbar"><Link to="/map"><ArrowLeft />返回地图</Link><span>路线清单</span><button className="icon-button" onClick={() => setCreating((value) => !value)} aria-label="新建路线"><Plus /></button></header>{creating && <form className="route-create" onSubmit={(event) => { event.preventDefault(); create.mutate() }}><input value={name} onChange={(event) => setName(event.target.value)} autoFocus /><button className="button button--primary">建立清单</button></form>}{routes.data?.map((route) => <section key={route.id} className="panel"><div className="panel__heading"><div>{editing === route.id ? <form className="route-rename" onSubmit={(event) => { event.preventDefault(); rename.mutate({ routeId: route.id, city: route.city }) }}><input value={editingName} onChange={(event) => setEditingName(event.target.value)} autoFocus /><button className="icon-button" aria-label="保存路线名称"><Pencil /></button><button type="button" className="icon-button" aria-label="取消改名" onClick={() => setEditing(undefined)}><X /></button></form> : <><h2>{route.name}</h2><span>{route.city || '全国地点'} · {route.places.length} 个地点 · 手动排序</span></>}</div><div className="route-heading-actions"><button className="icon-button" aria-label="重命名路线" onClick={() => { setEditing(route.id); setEditingName(route.name) }}><Pencil /></button><button className="icon-button" aria-label="删除路线" onClick={() => setDeleting({ id: route.id, name: route.name })}><Trash2 /></button></div></div>{route.places.map((place, index) => <div className="route-row" key={place.id}><span className="route-order">{index + 1}</span><MapPin /><div><strong>{place.name}</strong><span>{place.address}</span></div><span className="route-row__actions"><button onClick={() => move(route.id, route.places.map((item) => item.id), index, -1)} disabled={index === 0 || reorder.isPending} aria-label="上移"><ArrowUp /></button><button onClick={() => move(route.id, route.places.map((item) => item.id), index, 1)} disabled={index === route.places.length - 1 || reorder.isPending} aria-label="下移"><ArrowDown /></button><button onClick={() => reorder.mutate({ routeId: route.id, ids: route.places.filter((item) => item.id !== place.id).map((item) => item.id) })} aria-label={`从${route.name}移除`}><X /></button></span></div>)}<p className="route-note">只保存地点和人工顺序，不生成未经路线服务验证的距离与交通时间。</p></section>)}{deleting && <ConfirmDialog title="删除路线清单" description={`删除“${deleting.name}”不会删除其中的地点。`} confirmLabel="删除路线" danger pending={removeRoute.isPending} error={removeRoute.error instanceof Error ? removeRoute.error.message : ''} onCancel={() => setDeleting(undefined)} onConfirm={() => removeRoute.mutate(deleting.id)} />}</div>
}
