from enum import StrEnum


class AICapability(StrEnum):
    CLASSIFICATION = "CLASSIFICATION"
    STRUCTURED_EXTRACTION = "STRUCTURED_EXTRACTION"
    ENTITY_EXTRACTION = "ENTITY_EXTRACTION"
    TRANSCRIPT_CORRECTION = "TRANSCRIPT_CORRECTION"
    CHUNK_SUMMARIZATION = "CHUNK_SUMMARIZATION"
    GLOBAL_SYNTHESIS = "GLOBAL_SYNTHESIS"
    VERIFY = "VERIFY"
    CONFLICT_RESOLUTION = "CONFLICT_RESOLUTION"
    DOMAIN_TERM_EXTRACTION = "DOMAIN_TERM_EXTRACTION"
    DOMAIN_REASONING = "DOMAIN_REASONING"
    VISION = "VISION"
    DOCUMENT_VISION = "DOCUMENT_VISION"
    SCREENSHOT_UNDERSTANDING = "SCREENSHOT_UNDERSTANDING"


class AIExecutionMode(StrEnum):
    AUTO = "AUTO"
    LOCAL_ONLY = "LOCAL_ONLY"
    LOCAL_FIRST = "LOCAL_FIRST"
    REMOTE_FIRST = "REMOTE_FIRST"
    REMOTE_ONLY = "REMOTE_ONLY"


class AIQualityTarget(StrEnum):
    ECONOMY = "ECONOMY"
    BALANCED = "BALANCED"
    QUALITY = "QUALITY"
    LOCAL_PRIVATE = "LOCAL_PRIVATE"
    CUSTOM = "CUSTOM"


class AIPrivacyPolicy(StrEnum):
    NORMAL = "NORMAL"
    LOCAL_ONLY = "LOCAL_ONLY"


class AICachePolicy(StrEnum):
    USE = "USE"
    BYPASS = "BYPASS"
    REFRESH = "REFRESH"


class AIModelLocation(StrEnum):
    LOCAL = "LOCAL"
    REMOTE = "REMOTE"
