import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowLeft, Ban, Check, Circle, Clock3, ExternalLink, LoaderCircle, RotateCcw, Wifi, WifiOff } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'

import { api } from '../../lib/api'
import { formatBeijingDateTime } from '../../lib/time'
import { formatStepDuration, isTimelineCurrent, stepLabel } from './taskTimeline'

export function TaskDetailPage() {
  const { jobId = '' } = useParams()
  const navigate = useNavigate()
  const queryClient = useQueryClient()
  const [streamState, setStreamState] = useState<'live' | 'fallback' | 'closed'>('fallback')
  const job = useQuery({ queryKey: ['job', jobId], queryFn: () => api.job(jobId), refetchInterval: (query) => { const data = query.state.data; return data?.status === 'QUEUED' || data?.status === 'RUNNING' && streamState !== 'live' || data?.status === 'CANCELLED' && Boolean(data.worker_id) ? 3000 : false } })
  const replay = useQuery({ queryKey: ['job-replay-options', jobId], queryFn: () => api.replayOptions(jobId), enabled: Boolean(job.data), refetchInterval: (query) => job.data?.status === 'CANCELLED' && !query.state.data?.full_replay_available ? 3000 : false })
  const stepRetry = useMutation({ mutationFn: () => api.retryJobFromStep(jobId, replay.data!.replay_from_step!), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ['job', jobId] }); void queryClient.invalidateQueries({ queryKey: ['job-replay-options', jobId] }); void queryClient.invalidateQueries({ queryKey: ['jobs'] }) } })
  const fullRetry = useMutation({ mutationFn: () => api.retryJobFull(jobId), onSuccess: (result) => { void queryClient.invalidateQueries({ queryKey: ['jobs'] }); navigate(`/tasks/${result.job_id}`) } })
  const cancel = useMutation({ mutationFn: () => api.cancelJob(jobId), onSuccess: () => void queryClient.invalidateQueries({ queryKey: ['job', jobId] }) })
  useEffect(() => {
    if (!jobId || job.data?.status !== 'RUNNING') return
    const socket = new WebSocket(`${location.protocol === 'https:' ? 'wss' : 'ws'}://${location.host}/api/jobs/${jobId}/stream`)
    socket.onopen = () => setStreamState('live')
    socket.onmessage = () => { void queryClient.invalidateQueries({ queryKey: ['job', jobId] }); void queryClient.invalidateQueries({ queryKey: ['jobs'] }) }
    socket.onerror = () => setStreamState('fallback')
    socket.onclose = () => setStreamState((current) => current === 'live' ? 'closed' : current)
    return () => socket.close()
  }, [job.data?.status, jobId, queryClient])
  if (!job.data) return <div className="detail-loading">正在读取任务…</div>
  const stalled = job.data.runtime_state === 'STALLED'
  const partial = job.data.status === 'PARTIAL_SUCCESS'
  const stepReplayAvailable = Boolean(replay.data?.step_replay_available && replay.data.replay_from_step)
  const requestFullReplay = () => {
    const detail = ['RUNNING', 'QUEUED'].includes(job.data.status) ? '当前流程会先停止，并创建新的完整任务。' : '将创建新的完整任务。'
    if (window.confirm(`${detail}该操作会重新访问来源并调用模型，确定继续吗？`)) fullRetry.mutate()
  }
  const actionError = stepRetry.error || fullRetry.error
  return <div className="task-detail page-frame"><header className="detail-topbar"><Link to="/tasks"><ArrowLeft />返回任务</Link><span>运行详情</span><div><button onClick={() => cancel.mutate()} disabled={!['RUNNING', 'QUEUED'].includes(job.data.status)}><Ban />取消</button><button onClick={requestFullReplay} disabled={fullRetry.isPending}><RotateCcw />从头重新运行</button></div></header>{actionError && <p className="form-error task-action-error" role="alert">{actionError instanceof Error ? actionError.message : '重新运行失败'}</p>}<section className={`task-hero ${partial ? 'task-hero--partial' : ''}`}><h1>{job.data.title}</h1><p><span className="status-dot" />{partial ? '处理流程已完成' : `${statusLabel(job.data.status)} · ${job.data.progress}%`}</p>{partial && <small>{job.data.completion_summary || '所有处理步骤已完成；部分补充信息待处理'}</small>}<div className="progress-track"><span style={{ width: `${job.data.progress}%` }} /></div></section>{job.data.error && <section className="task-error-card"><strong>{job.data.error_code || 'TASK_ERROR'}</strong><span>{job.data.error}<small>{interventionHint(job.data.error_code)}</small></span><Link to={`/logs?job_id=${encodeURIComponent(jobId)}`}>查看关联日志 <ExternalLink /></Link></section>}
    {['FAILED', 'NEEDS_USER', 'CANCELLED'].includes(job.data.status) && replay.data && <section className={`task-replay-card ${stepReplayAvailable ? '' : 'task-replay-card--expired'}`}><div><strong>{stepReplayAvailable ? '可从失败步骤继续' : '步骤续跑不可用'}</strong><span>{stepReplayAvailable ? `前面 ${replay.data.reused_steps.length} 个已完成步骤不会再次执行；将从“${stepLabel(replay.data.replay_from_step ?? '')}”开始顺次运行。` : `${replay.data.reason || '没有可续跑的失败步骤'}。如需完整重跑，请使用右上角“从头重新运行”。`}</span></div>{stepReplayAvailable && <button className="button button--primary" onClick={() => stepRetry.mutate()} disabled={stepRetry.isPending || replay.isPending}><RotateCcw />从“{stepLabel(replay.data.replay_from_step ?? '')}”继续</button>}</section>}
    {job.data.status === 'RUNNING' && <section className={`task-live-card ${stalled ? 'task-live-card--stalled' : ''}`}><div className="task-live-card__primary"><span>{stalled ? '当前处理 · 任务可能停滞' : '当前处理'}</span><strong>{stepLabel(job.data.current_step)}</strong><small>{job.data.current_step} · {stalled ? '该任务未报告后续进度' : job.data.current_step_message || '执行器正在等待下一条活动事件'}</small></div><div><label>开始于</label><b>{formatDateTime(job.data.current_step_started_at)}</b></div><div><label>该任务最后活动</label><b className={stalled ? 'amber-text' : ''}>{relativeTime(job.data.last_activity_at)}</b></div><div><label>Worker</label><b>{job.data.worker_id || '等待领取'}</b></div><div><label>事件连接</label><b className={streamState === 'live' ? 'green-text' : 'amber-text'}>{streamState === 'live' ? <><Wifi />实时</> : <><WifiOff />轮询</>}</b></div><Link className="task-live-card__logs" to={`/logs?job_id=${encodeURIComponent(jobId)}`}><ExternalLink />{stalled ? '查看日志 / 重试' : '查看关联日志'}</Link></section>}
    <div className="task-detail-grid"><section className="panel"><div className="panel__heading"><h2>运行时间线</h2><span>{streamState === 'live' ? '实时更新' : '每 3 秒刷新'}</span></div>{job.data.steps.map((step) => <div className={`timeline-row ${isTimelineCurrent(job.data.status, job.data.current_step, step.name, step.status) ? 'timeline-row--current' : ''} ${isTimelineCurrent(job.data.status, job.data.current_step, step.name, step.status) && stalled ? 'timeline-row--stalled' : ''}`} key={step.name}>{['COMPLETED', 'REUSED'].includes(step.status) ? <Check /> : step.status === 'RUNNING' ? <LoaderCircle className="spin" /> : <Circle />}<div><strong>{stepLabel(step.name)}</strong><span>{step.name} · {isTimelineCurrent(job.data.status, job.data.current_step, step.name, step.status) && stalled ? '任务可能停滞' : statusLabel(step.status)}{['COMPLETED', 'REUSED'].includes(step.status) ? ' · 100%' : step.status === 'RUNNING' ? ` · ${step.progress > 0 ? `${step.progress}%` : '进行中'}` : ''} · {formatStepDuration(step.started_at, step.finished_at)}</span>{isTimelineCurrent(job.data.status, job.data.current_step, step.name, step.status) && !step.error && <small className="timeline-row__detail"><Clock3 />{stalled ? `开始于 ${formatDateTime(step.started_at)} · 该任务 ${relativeTime(job.data.last_activity_at, false)}未更新` : latestStepEvent(job.data.events, step.name) || '进行中，等待下一项活动'}</small>}{step.error && <small className="timeline-row__error">{step.error}</small>}</div><em>{isTimelineCurrent(job.data.status, job.data.current_step, step.name, step.status) && stalled ? '需关注' : statusLabel(step.status)}</em></div>)}</section><aside className="panel task-summary"><h2>运行摘要</h2><dl><dt>任务状态</dt><dd className={stalled ? 'amber-text' : ''}>{partial ? '处理流程已完成' : stalled ? '任务可能停滞' : statusLabel(job.data.status)}</dd>{job.data.error_code && <><dt>错误代码</dt><dd className="amber-text" title={job.data.error_code}>{job.data.error_code}</dd></>}<dt>任务类型</dt><dd>{jobTypeLabel(job.data.job_type)}</dd><dt>{job.data.status === 'RUNNING' ? '当前步骤' : '结束步骤'}</dt><dd>{stepLabel(job.data.current_step)}</dd><dt>最近模型调用</dt><dd>{job.data.model_step ? stepLabel(job.data.model_step) : '本任务尚未调用模型'}</dd><dt>Provider</dt><dd title={job.data.provider || ''}>{job.data.provider || '—'}</dd><dt>模型</dt><dd title={job.data.model || ''}>{job.data.model || '—'}</dd><dt>重试次数</dt><dd>{job.data.retry_count}</dd><dt>Worker</dt><dd title={job.data.worker_id || ''}>{job.data.worker_id || '—'}</dd><dt>该任务最后活动</dt><dd>{relativeTime(job.data.last_activity_at)}</dd></dl></aside></div></div>
}

function jobTypeLabel(type: string) { return ({ RECRUITMENT: '招聘', TRAVEL: '旅行', UNKNOWN: '待识别' } as Record<string, string>)[type] ?? type }
function statusLabel(status: string) { return ({ QUEUED: '排队中', RUNNING: '处理中', COMPLETED: '已完成', REUSED: '已复用', PARTIAL_SUCCESS: '部分完成', SKIPPED: '已跳过', FAILED: '失败', NEEDS_USER: '需确认', CANCELLED: '已取消' } as Record<string, string>)[status] ?? status }
function relativeTime(value: string | null, suffix = true) { if (!value) return '暂未采集'; const seconds = Math.max(0, Math.round((Date.now() - new Date(value).getTime()) / 1000)); const label = seconds < 60 ? `${seconds} 秒` : seconds < 3600 ? `${Math.floor(seconds / 60)} 分钟` : seconds < 86400 ? `${Math.floor(seconds / 3600)} 小时` : `${Math.floor(seconds / 86400)} 天`; return suffix ? `${label}前` : label }
function formatDateTime(value: string | null) { return value ? formatBeijingDateTime(value, { month: 'numeric', day: 'numeric' }) : '等待开始' }
function latestStepEvent(events: Array<{ message: string; detail: Record<string, unknown> }>, step: string) { return events.find((event) => event.detail.step === step)?.message }
function interventionHint(code: string | null) { return ({ ATTEMPT_TIMEOUT: '该步骤长时间未更新。先查看关联日志中的最后一个 phase，再重试。', VIDEO_METADATA_FAILED: '请确认 Bilibili 链接可在本机网络打开后重试。', VIDEO_LOGIN_REQUIRED: '请在设置中补充合法 Bilibili Cookie 后重试。', VIDEO_MEDIA_UNAVAILABLE: '请检查视频访问权限、Cookie 与网络后重试。' } as Record<string, string>)[code ?? ''] ?? '请查看关联日志中的阶段与错误原因，再决定是否重试。' }
